### ISSUE TITLE
Outputting valid code

### ISSUE THREAD

**Issue by StevenLangbroek** [splittingred/Gallery#2]
The ampersands in the source of my thumbs and in my image-links are being outputted in invalid format (ampersand hasn't been converted to &amp;). Is this a possibility? Thanks!

**Comment by Nacnud** [comment]
This is a more general problem as it applies to all Gallery URLs.
It can be worked around by editing pre-defined chunks galAlbumRowTpl and galItemThumb; and creating two custom chunks galItemAlbum and galItemTag. The purpose of these chunks is to swap '?' for '&'. I've added details into the Gallery 0.1.0 rc2 Support thread.
The '&' is needed if MODx is used in default configuration and '?' is needed is Search Engine Friendly URLs are being generated.
The fix is probably to create the URL's in the snippet; doing it in the chunk will be fairly verbose and prone to user error.

**Comment by splittingred** [comment]
Fixed in 0.1.1-pl
