### ISSUE TITLE
[FR] do not override images with batch upload

### ISSUE THREAD

**Issue by djemmers** [splittingred/Gallery#28]
update image folder,

I automaitcally add images in my image folder through other sites.
So I need to update my albums.
I would like to use batch upload and point to the (existing) folder.
but then it overrides the old entries and I loose the tag information.

any way to let it check wether the the images are allready inthere an if they are, not to update so the tags are kept?

**Comment by jobatkin** [comment]
I've also had issues when using both the batch uploader and the item uploader. I originally uploaded most of the album items via the batch uploader (uploaded to a different directory than the default files/2010/10), but then wanted to add some more. I thought initially that I could do this by redoing the batch upload, but this duplicated my existing photos as well as adding the new ones (could this be fixed so it just finds the new ones?).
So I deleted the duplicates, then next time I needed to add more I used the single Upload Item option (which goes to the default files/2010/10 directory). Somehow using the combination of both caused some confusion, because in the database all the item paths go to the default directory, and most of those that were in the original batch upload directory showed as broken links in IE (not Chrome though, to add to the confusion!).

In future I'll make sure I put batch uploaded files in the default directory, but ideally I'd like to have my different album images in different directories, and would love to be able to batch upload to existing albums without duplicating the existing images.

**Comment by boombana** [comment]
I'm experiencing a similar issue with the batch uploader overwriting images in the files directory (ie; assets/components/gallery/files/2011/02/).

If you load a batch of images and then load another batch with the same filenames as the first lot they will be overwritten.

I applied a clunky temporary fix to get me out of a pickle. Added date('U') to $dateFolder string in these files:
core/components/gallery/processors/mgr/item/batchupload.php
core/components/gallery/model/gallery/galitem.class.php 

 $dateFolder = date('Y').'/'.date('m').'/'.date('U').'/';

**Comment by splittingred** [comment]
Fixed by moving items to album-centric storage:
https://github.com/splittingred/Gallery/commit/8e8e53f9534e74d590ef714d5622e774bc2aac53
