### ISSUE TITLE
Gallery only works fine in 'web' context

### ISSUE THREAD

**Issue by Hori76** [splittingred/Gallery#34]
If you use the gallery component in a context (subdomain), the images link to assets/... so they don't show in the subdomain.
There should be a possibility to link the images to the head domain or a separate folder in the subdomain.

**Comment by gee-smg** [comment]
just a tot.
create your own TV with value your main domain eg: http://example.com
 global_domain_URL = http://example.com
call base href parameter with your TV value,<base href="[[*global_domain_URL]]" /> in every head of template on your subdomain.

(code in your subdomain template, remove the "" ) :

<''head'''>
<'''base href="[[!*global_domain_URL]]" /'''>
...........
...........
<""/head"">
<""body"">



<''''img src=assets/images/pic_1.jpg /'''> 

<''''--since the base href is your main domain,
the image will go to http://example.com/assets/images/pic_1.jpg INSTEAD of 
http://subdomain.example.com/assets/images/pic_1.jpg which is physically not existed in
the directory
--'''>

</'''body'''>

**Comment by Hori76** [comment]
Thanks, I know that this works, but it's not really a nice solution if you've got a context with a completely different website, which has nothing to do with the primary context. Every context should have his own gallery with its own domain
