### ISSUE TITLE
imageHeight paramter isn't working in call anymore

### ISSUE THREAD

**Issue by StevenLangbroek** [splittingred/Gallery#4]
I've called the Gallery as following: 

[[Gallery?album=`[[+album]]`&containerTpl=`galleryContainerTpl`&thumbTpl=`galleryThumbTpl`&thumbHeight=`73`&useCss=`false`&imageHeight=`700`]]

But imageHeight doesn't do anything. Site is live @ www.your-identity.info.

**Comment by splittingred** [comment]
How are you displaying the image? It works on Gallery, but you shouldnt be displaying the image itself with that variable.

&imageHeight really only applies if you're using the Galleriffic plugin. Otherwise, use [[GalleryItem]] to display an image, or set the thumb height bigger, or override the tpl.

**Comment by StevenLangbroek** [comment]
Well, I think it was a great feature to be allowed to pass that even if you don't use Gallerrific, if the image is being passed through phpThumb anyway...
