### ISSUE TITLE
thumbFar has no effect

### ISSUE THREAD

**Issue by maciej-ludwinski** [splittingred/Gallery#71]
thumbFar has no effect on the thumbnail (the same goes for imageFar on images).

Issue on MODx Revolution 2.0.8-pl
Other versions not tested.

I've been at this for the better part of a day now and can't figure it out. Don't know even if it's an issue with Gallery, modX or phpThumb. 

Please advice where to search for a solution or a workaround.

**Comment by splittingred** [comment]
Fixed in this commit: https://github.com/splittingred/Gallery/commit/649e9e2a99d14bb44af115ad49a2bfa85ba1f240

**Comment by maciej-ludwinski** [comment]
Nope, the problem was elsewhere. 
In /core/model/phpthumb/phpthumb.class.php on line 1366 there was:
switch (strtoupper($this->zc)) {
but should be:
switch (strtoupper($this->far)) {

It took zc, which was 1 and went default.

**Comment by miduku** [comment]
I have the same issue here. Is there another way to solve this since messing with the core php files isn't really the best sollution and `switch (strtoupper($this->zc)) {` hasn't been changed to `switch (strtoupper($this->far)) {` ?

## 

Using **Revo 2.2.0-pl2 (advanced)** and **Gallery 1.4.0 rc1**
